name = "Enhanced Vanilla"
author = "Hikiru"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b32b938542fe0c33330249d5eeab2d375f96dbb178bf4e60ea9657a5dc2ce16d"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
