name = "Enhanced Vanilla"
author = "Hikiru"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "caccb3ed5114699ed89b943adf1dc3cedcb6b562e81c8082566805c17f79ab71"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
