name = "Enhanced Vanilla"
author = "Hikiru"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "368301ef15820d99d9fa80d0132c2114eb3a9cab12671d157a17a75271feed79"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
