name = "Enhanced Vanilla"
author = "Hikiru"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c2b13047b3dafabcc6acd134b73f6902a179a456b356c63205a13efa2ffe89d"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
