name = "KermitCraft II"
author = "Hikiru"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a01102c704f852611788f78d64cf3fff0bb0ba7a709a9df1059b058a5269bbd5"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
