name = "Enhanced Vanilla"
author = "Hikiru"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "451afe31b05f35e5d545032de027593d0727126eaba58b4deac1d68c8f3e969e"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
