name = "KermitCraft II"
author = "Hikiru"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a9be033a7baf46737c5552dd518adacd4c383307046ab9f21111e28ecaf8766"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
